# Generated by Django 6.0 on 2025-12-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Сourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите курс", max_length=255, verbose_name="Курс"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="содержимое урока",
                        null=True,
                        verbose_name="содержимое",
                    ),
                ),
                (
                    "course_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение курса",
                        null=True,
                        upload_to="lms/curse_image",
                        verbose_name="Изображение курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите урок", max_length=255, verbose_name="Урок"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="содержимое урока",
                        null=True,
                        verbose_name="содержимое",
                    ),
                ),
                (
                    "lesson_image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение урока",
                        null=True,
                        upload_to="lms/lessons_image",
                        verbose_name="Изображение урока",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True,
                        help_text="Добавьте ссылку на урок",
                        null=True,
                        verbose_name="Ссылка ну урок",
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course",
                        to="lms.сourse",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
